# Generated by Django 5.0.7 on 2024-10-06 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='The full name of the company', max_length=255, verbose_name='Company Name')),
                ('email', models.EmailField(help_text='The main contact email for the company', max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(help_text='The main contact phone number for the company', max_length=15, verbose_name='Phone Number')),
                ('address', models.CharField(blank=True, default='Your Address', help_text='The street address of the company', max_length=700, null=True, verbose_name='Street Address')),
            ],
            options={
                'verbose_name_plural': 'Company Information',
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copyright', models.CharField(blank=True, help_text='The copyright notice to display in the footer', max_length=500, null=True, verbose_name='Copyright Text')),
            ],
            options={
                'verbose_name_plural': 'Footer',
            },
        ),
        migrations.CreateModel(
            name='SiteLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, default='default/favicon.ico', help_text='Upload the logo of the company', null=True, upload_to='company/logo/', verbose_name='Company Logo')),
                ('favicon', models.ImageField(blank=True, default='default/favicon.ico', help_text='Upload the favicon for the website', null=True, upload_to='company/logo/', verbose_name='Favicon')),
            ],
            options={
                'verbose_name_plural': 'Site Logo',
            },
        ),
    ]
