# Generated by Django 5.0.7 on 2024-10-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'About'},
        ),
        migrations.AlterModelOptions(
            name='aboutlist',
            options={},
        ),
        migrations.AddField(
            model_name='about',
            name='aboutlist',
            field=models.ManyToManyField(to='about.aboutlist'),
        ),
        migrations.AlterField(
            model_name='aboutlist',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
